{% set version = "2.11" %}

package:
  name: pyicu
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyICU/PyICU-{{ version }}.tar.gz
  sha256: 3ab531264cfe9132b3d2ac5d708da9a4649d25f6e6813730ac88cf040a08a844

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Also pin icu here so that the version is consistent with host.
    # otherwise, finding the correct icu seems to fail on OSX-64
    - icu
  host:
    - python
    - pip
    - cld2-cffi
    - icu
  run:
    - python
    - cld2-cffi

test:
  commands:
    - python -c "from icu import Locale;locale = Locale('pt_BR')"

about:
  home: https://github.com/ovalhub/pyicu
  license: OTHER
  license_family: OTHER
  license_file: LICENSE
  summary: Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.

  description: |
    Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.
    ICU stands for "International Components for Unicode". These are the i18n
    libraries of the Unicode Consortium. They implement much of the Unicode Standard,
    many of its companion Unicode Technical Standards, and much of Unicode CLDR.
  doc_url: https://gitlab.pyicu.org/main/pyicu
  dev_url: https://gitlab.pyicu.org/main/pyicu

extra:
  recipe-maintainers:
    - rxm7706
    - cu8blank
