{% set version = "2.8.1" %}

package:
  name: pyicu
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyICU/PyICU-{{ version }}.tar.gz
  sha256: f0b9549a87f87ba7c413f13679d137271e0b37f1f39b0109ace38257d4d148d6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cld2-cffi
    - icu
  run:
    - python
    - cld2-cffi
    - icu

test:
  commands:
    - python -c "from icu import Locale;locale = Locale('pt_BR')"

about:
  home: https://github.com/ovalhub/pyicu
  license: OTHER
  license_family: OTHER
  license_file: LICENSE
  summary: Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.

  description: |
    Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.
    ICU stands for "International Components for Unicode". These are the i18n
    libraries of the Unicode Consortium. They implement much of the Unicode Standard,
    many of its companion Unicode Technical Standards, and much of Unicode CLDR.
  doc_url: https://github.com/ovalhub/pyicu
  dev_url: https://github.com/ovalhub/pyicu

extra:
  recipe-maintainers:
    - cu8blank
